# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('notes', models.ManyToManyField(blank=True, default=None, to='notes.Note')),
            ],
        ),
    ]
