# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=63)),
            ],
        ),
    ]
