# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_requestmy'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmy',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
